DROP PROCEDURE `MOVE_WARENTRAEGER_TO_SEKTOR`;
DROP PROCEDURE `MOVE_WARENTRAEGER_TO_TRANSPORTBAND`;
DROP PROCEDURE `UPDATE_ROBOTER_WERKZEUG`;
DROP PROCEDURE `UPDATE_ROBOTER_SEKTOR`;
DROP PROCEDURE `UPDATE_ARTIKEL_WARENTRAEGER`;


DROP TABLE Roboter_Werkzeug;
DROP TABLE Roboter_Sektor;
DROP TABLE Transportband_Warentraeger;
DROP TABLE Sektor_Warentraeger;
DROP TABLE Artikel_Warentraeger;
DROP TABLE Hubquerpodest_Hubquerpodest;
DROP TABLE Hubquerpodest;
DROP TABLE Hubpodest;
DROP TABLE Werkzeug;
DROP TABLE Gelenk;
DROP TABLE Roboter;
DROP TABLE Sensor;
DROP TABLE Transportband;
DROP TABLE Artikel;
DROP TABLE Warentraeger;
DROP TABLE Sektor;